version: "3.7"
services:
#  api:
#    image: jeffrygonzalez/libraryapi:latest
#    depends_on:
#      - sql
#    ports: 
#      - 8080:80
#    environment:
#      - ConnectionStrings__Library=server=sql;database=Library_Prod;user=sa;password=TokyoJoe138!
#  sql:
#    image: jeffrygonzalez/librarysql-mar-2021:latest
#    ports:
#      - 1433:1433
  cache: 
    image: redis:latest
    ports:
      - 6379:6379
  messaging:
    image: rabbitmq:management
    ports:
      - 15671:15671
      - 15672:15672
      - 5672:5672