version: "3.7"
services:
  api:
    image: jeffrygonzalez/libraryapi-apr2021:latest
    ports:
      - 80:80
    environment:
      - ConnectionStrings__library=server=TODO;
      - ConnectionString__redis=cache
      - Rabbit:HostName=messaging
      - Rabbit:UserName=guest
      - Rabbit:Password=guest
      - Rabbit:Port=5672
      - Rabbit:VHost=/
  cache:
    image: redis:latest
    ports:
      - 6379:6379
  messaging:
    image: rabbitmq:managent
    ports:
      - 15671:15671
      - 15672:15672
      - 5672:5672
  reservationprocessor:
    image: jeffrygonzalez/reservationprocessor-apr-2021:latest
    depends_on:
      - messaging
    environment:
      - apiUrl=http://TODO
      - Rabbit:HostName=messaging
      - Rabbit:UserName=guest
      - Rabbit:Password=guest
      - Rabbit:Port=5672
      - Rabbit:VHost=/
  